name = "git"

[params.short]
flag = [ "p" ]
path = [ "C" ]
keyvalue = [ "c" ]

[params.long]
path = [
    "git-dir",
    "work-tree",
]
flag = [
    "version",
    "help",
    "html-path",
    "man-path",
    "info-path",
    "paginate",
    "no-pager",
    "no-replace-object",
    "bare",
]
path_optional = [
    "exec-path",
]
string = [
    "namespace",
]
file = [
    [ "test", ".txt", ".md" ],
]

[[commands]]
name = "add"
end_of_params = "--"
after_params = [ "array", "path" ]

    [commands.params.short]
    flag = [ "v", "n", "f", "i", "p", "e", "u", "N", ]

    [commands.params.long]
    flag = [
        "verbose",
        "dry-run",
        "force",
        "interactive",
        "patch",
        "edit",
        "all",
        "no-all",
        "ignore-removal",
        "no-ignore-removal",
        "update",
        "intent-to-add",
        "refresh",
        "ignore-errors",
        "ignore-missing",
        "renormalize",
    ]

[[commands]]
name = "commit"

[[commands]]
name = "checkout"
