name = "git"

[params.short]
flag = [ "p" ]
path = [ "C" ]
keyvalue = [
    [   "c",
        "advice.pushUpdateRejected",
        "advice.pushNonFFCurrent",
        "core.editor",
    ],
]

[params.long]
flag = [
    "version",
    "help",
    "html-path",
    "man-path",
    "info-path",
    "paginate",
    "no-pager",
    "no-replace-object",
    "bare",
    "literal-pathspecs",
    "glob-pathspecs",
    "noglob-pathspecs",
    "icase-pathspecs",
    "no-optional-locks",
]
path = [
    "git-dir",
    "work-tree",
    "namespace",
    "super-prefix",
]
path_optional = [
    "exec-path",
]
file = [
    [ "test", ".txt", ".md" ],
]

[[commands]]
name = "add"
end_of_params = "--"
after_params = [ "array", "path" ]

    [commands.params.short]
    flag = [ "v", "n", "f", "i", "p", "e", "u", "N", ]

    [commands.params.long]
    flag = [
        "verbose",
        "dry-run",
        "force",
        "interactive",
        "patch",
        "edit",
        "all",
        "no-all",
        "ignore-removal",
        "no-ignore-removal",
        "update",
        "intent-to-add",
        "refresh",
        "ignore-errors",
        "ignore-missing",
        "renormalize",
    ]


[[commands]]
name = "branch"

    [commands.params.short]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]

    [commands.params.long]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]


[[commands]]
name = "checkout"

    [commands.params.short]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]

    [commands.params.long]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]


[[commands]]
name = "clone"

    [commands.params.short]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]

    [commands.params.long]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]


[[commands]]
name = "commit"

    [commands.params.short]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]

    [commands.params.long]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]


[[commands]]
name = "fetch"

    [commands.params.short]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]

    [commands.params.long]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]


[[commands]]
name = "init"

    [commands.params.short]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]

    [commands.params.long]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]


[[commands]]
name = "merge"

    [commands.params.short]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]

    [commands.params.long]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]


[[commands]]
name = "pull"

    [commands.params.short]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]

    [commands.params.long]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]


[[commands]]
name = "push"

    [commands.params.short]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]

    [commands.params.long]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]


[[commands]]
name = "rebase"

    [commands.params.short]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]

    [commands.params.long]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]


[[commands]]
name = "reset"

    [commands.params.short]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]

    [commands.params.long]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]


[[commands]]
name = "show"

    [commands.params.short]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]

    [commands.params.long]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]


[[commands]]
name = "stash"

    [commands.params.short]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]

    [commands.params.long]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]


[[commands]]
name = "status"

    [commands.params.short]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]

    [commands.params.long]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]


[[commands]]
name = "submodule"

    [commands.params.short]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]

    [commands.params.long]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]


[[commands]]
name = "config"

    [commands.params.short]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]

    [commands.params.long]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]


[[commands]]
name = "remote"

    [commands.params.short]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]

    [commands.params.long]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]


[[commands]]
name = "help"

    [commands.params.short]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]

    [commands.params.long]
    flag = [ "" ]
    file = [ [ "" ] ]
    keyvalue = [ [ "" ] ]
    path = [ "" ]
    path_optional = [ "" ]
    string = [ [ "", ""] ]
